### ISSUE TITLE
What is the state of  1-Step Traffic Junction

### ISSUE THREAD

**Issue by GoingMyWay** [mzho7212/LICA#2]
Hi,

What is the state of 1-Step Traffic Junction? Will you share the code of 1-Step Traffic Junction?

**Comment by mzho7212** [comment]
Hi, 

Thanks for your interest in our work! In 1-step Traffic Junction env, since there is only one possible state, we don't actually need to formulate a state vector. (We do however need to include an agent id to distinguish the agents.)

We just made an update on the repo to add the implementation for 1-step Traffic Junction env. Please check https://github.com/mzho7212/LICA/tree/main/1_step_traffic_junction

Hope this helps.

**Comment by GoingMyWay** [comment]
@mzho7212 

Thanks for sharing. Thanks again.
